# conf/config.yaml
paths:
  VFR_syn_train_path: "/public/dataset/AdobeVFR/Raw Image/VFR_syn_train"
  VFR_syn_train_hdf5_path: "/public/dataset/AdobeVFR/hdf5/VFR_syn_train.hdf5"
  VFR_syn_font_list_path: "/public/dataset/AdobeVFR/fontlist.txt"
  scae_weights_path: "/weights/scae_weights.pth"
  cls_weights_path: "/weights/"

training:
  DEVICE: "cuda"
  BATCH_SIZE: 4096
  EPOCHS: 100
  NUMBER_OF_WORKERS: 4
  PREFETCH_FACTOR: 2
  LEARNING_RATE: 1e-4
  
model:
  - model: resnet
